new big refactoring: extract function + extract Dialog class
TGLuis/compteurDeLaRoulotte pull request #7
Opened 2020-09-16 22:22 UTC by TGLuis

use the heuristic: 
a function should fit in one screen
and try to make the code cleaner

2020-09-19 10:48 UTC, FrancoisDuchene requested changes
### Bon travail ! 
Je n'ai pas grand-chose à redire, à part certains renommages de variables et une demande de documentation pour **Dialogs**.
J'ai également essayé de trouver des points à améliorer mais qui ne doivent pas forcément trouver une implémentation dans cette PR, au moins être sujet à discussion

2020-09-19 10:48 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/CounterFragment.kt
> +    private fun saveCounter() {
#### Suggestion
Au lieu d'avoir la fonction pour sauvegarder les propriétés d'un compteur dans un **fragment**, est-ce que ça ne serait pas mieux si elle était dans l'objet *Counter* directement ?

2020-09-19 10:48 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/CounterFragment.kt
> +    private fun getNumberOfChanges(): Pair<Int, String>  {
#### Suggestion
Je sais pas si c'est une bonne idée, mais cette fonction pourrait très facilement être remplacée par une fonction statique (avec *isChanged* donné en argument) et par conséquent, pourrait être bougée dans une autre classe.

2020-09-19 10:48 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/HelpFragment.kt
> +    private fun listener(b: Boolean, tv: TextView, ib: ImageButton, text: Int, height: Int): Boolean {
#### Pour le futur
Y a moyen d'aller encore plus loin dans le refractor et de mettre les fonctions *listener*, *dropUp* et *dropDown* dans une classe à part, pour que ça puisse être réutiliser autre part dans l'app.

2020-09-19 10:48 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/ParametersFragment.kt
> +        val array = ArrayList(Helper.languagesAvailable())
#### Renommage
Peut-être qu'un nom plus explicite serait plus approprié que *array*. Par exemple *"availableLanguages"*

2020-09-19 10:48 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
>              buttonM.setOnClickListener {
#### Pour le futur
Il y a moyen de faire un objet listener qui pourrait généraliser l'utilisation de bruitage avec du high-order programming
Par exemple un truc du genre ;
```kotlin
fun (context, media, functionAfter: () -> Unit) : OnClickListener  {
      if ((context as MainActivity).volumeOn)
          media.start()
      functionAfter()
}
```

2020-09-19 10:48 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
>              } else if (b || (!b && count.etat > 0)) {
#### Renommage
Renommer la fonction **up** qui peut créer de la confusion avec l'autre fonction **up** contenu dans la classe au-dessus. Par exemple en **secondaryUp**

2020-09-19 10:48 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
>      private fun up(b: Boolean) {
#### Renommage
Pareil que pour la ligne 110, renommer par ex en **primaryUp**

2020-09-19 10:48 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/library/Dialogs.kt
> +
#### Documentation
Ça serait bien d'ajouter un peu de doc pour chaque fonction, au moins une ligne expliquant ce qu'elle fait, pour différencier rapidement les fonctions qui ont des comportements similaires

2020-09-19 10:48 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/library/Helper.kt
> +        return listOf("-", "FR", "NL", "EN")
#### Question
Quel est l'utilité de ce symbole ?

2020-09-19 21:47 UTC, TGLuis commented on lecompteurdelaroulotte/app/src/main/java/fragments/CounterFragment.kt
> +    private fun saveCounter() {
Peut-être mais certainement pas la fonction telle qu'elle est là. Il faudrait enlever tout rapport avec context, pcq un compteur ne doit pas avoir conscience du contexte.

2020-09-19 21:47 UTC, TGLuis commented on lecompteurdelaroulotte/app/src/main/java/fragments/CounterFragment.kt
> +    private fun getNumberOfChanges(): Pair<Int, String>  {
A réfléchir effectivement pour voir les implication et la possible implémentation!

2020-09-19 21:48 UTC, TGLuis commented on lecompteurdelaroulotte/app/src/main/java/fragments/HelpFragment.kt
> +    private fun listener(b: Boolean, tv: TextView, ib: ImageButton, text: Int, height: Int): Boolean {
yep, mais je pensais faire une chose à la fois ;) ça me semblait déjà pas mal

2020-09-19 21:49 UTC, TGLuis commented on lecompteurdelaroulotte/app/src/main/java/fragments/ParametersFragment.kt
> +        val array = ArrayList(Helper.languagesAvailable())
ofc :)
Tu veux que je change dans cette PR ou plus tard?

2020-09-19 21:50 UTC, TGLuis commented on lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
>              buttonM.setOnClickListener {
bonne idée :)
Même réflexion, mnt ou plus tard? @FrancoisDuchene

2020-09-19 21:51 UTC, TGLuis commented on lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
>              } else if (b || (!b && count.etat > 0)) {
Bonne idée!

2020-09-19 21:51 UTC, TGLuis commented on lecompteurdelaroulotte/app/src/main/java/library/Dialogs.kt
> +
yep bonne idée :+1:

2020-09-19 21:53 UTC, TGLuis commented on lecompteurdelaroulotte/app/src/main/java/library/Helper.kt
> +        return listOf("-", "FR", "NL", "EN")
C'est le symbole ajouté par défaut, qui représente le fait que c'est le language par défaut du gsm ou anglais si aucun ne correspond (il faudra peut-être débugger pour être sûr) mais tu peux voir que normalement je mets "-" par défaut dans le fichier de config.

2020-09-20 07:44 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/CounterFragment.kt
> +    private fun saveCounter() {
Il suffirait pas de modifier l'array *isChanged* pour qu'il contienne aussi les différentes strings associées ?
Par ex : isChanged["name"] = Pair(  true, R.string.counter_name) ?

2020-09-20 07:47 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/HelpFragment.kt
> +    private fun listener(b: Boolean, tv: TextView, ib: ImageButton, text: Int, height: Int): Boolean {
Oui oui je me doute, c'est juste pour réfléchir pour faire un pas plus loin, pas forcément qu'on devait le faire maintenant :)

2020-09-20 07:47 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/ParametersFragment.kt
> +        val array = ArrayList(Helper.languagesAvailable())
Autant faire dans cette PR directement je dirais, comme ça c'est fait

2020-09-20 07:49 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
>              buttonM.setOnClickListener {
Je dirais maintenant parce que je ne crois pas que ça prenne bcp de temps

2020-09-20 07:50 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/library/Helper.kt
> +        return listOf("-", "FR", "NL", "EN")
Ça fait sens, merci !

2020-09-20 09:05 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/CounterFragment.kt
> +    private fun saveCounter() {
Finalement je pense que ce n'était pas une si bonne idée que ça, je propose de laisser comme ça pour l'instant

2020-09-20 09:09 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/CounterFragment.kt
> +    private fun getNumberOfChanges(): Pair<Int, String>  {
Je propose de remettre ça à plus tard, ça m'a l'air plutôt compliqué à refractor comme je le pensais et je ne sais pas si ça serait très utile

2020-09-20 14:06 UTC, TGLuis commented on lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
> +                Log.e(TAG, "OHOH")
Hoho?

2020-09-20 14:06 UTC, TGLuis commented on lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
> +            Log.e(TAG, "pomme")
pomme?

2020-09-20 14:06 UTC, TGLuis commented on lecompteurdelaroulotte/app/src/main/java/library/Listeners.kt
> +        }
ça n'a pas besoin de retourner la View.OnClickListener puisque tu l'appelles entre {} et pas entre ()...
Tu devrais juste exécuter les lignes sans retourner je pense...

2020-09-21 15:52 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
>              buttonM.setOnClickListener {
Bon du coup j'ai essayé de faire ça, ça n'a pas l'air de marcher pour une raison qui m'échappe, et mes connaissances en metaprogramming en Kotling étant limitées, je ne sais pas comment avancer. Basiquement, cette fonction n'est pas appelée quand je l'assigne en tant que nouveau listener

2020-09-21 15:54 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
> +                Log.e(TAG, "OHOH")
Log de test que j'ai push sans faire gaffe. J'essayé de testé le fonctionnement du listener sur le media

2020-09-21 15:54 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
> +            Log.e(TAG, "pomme")
idem que pour l'autre log

2020-09-21 15:55 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/library/Listeners.kt
> +        }
Je vais tenter ça, en tout cas en l'état actuel ça ne fonctionne pas

2020-09-21 16:21 UTC, FrancoisDuchene commented on lecompteurdelaroulotte/app/src/main/java/library/Listeners.kt
> +        }
ça n'a pas l'air de changer grand-chose

2020-09-21 20:24 UTC, TGLuis commented
Better now @FrancoisDuchene ?

2020-09-23 15:15 UTC, merged